version: '3.7'

services:

  web_client:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - '3000-3001:3000-3001'
    restart: always

  web_server:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - '8080-8084:8080'
    volumes:
      - ./server/var:/usr/src/app/var/
    links:
      - redis
    restart: always

  redis:
    image: redis

  nginx:
    image: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - '80:9090'
    links:
      - web_server
    restart: always
