export const AUTH_REGISTRATION = 'AUTH_REGISTRATION';
export const AUTH_LOGIN = 'AUTH_LOGIN';
export const CREATE_NEW_USER = 'CREATE_NEW_USER';
export const GET_USER_BY_ID = 'GET_USER_BY_ID';

export const REQUEST_GET_USER_BY_ID = 'REQUEST_GET_USER_BY_ID';
export const SUCCESS_GET_USER_BY_ID = 'SUCCESS_GET_USER_BY_ID';
export const FAIL_GET_USER_BY_ID = 'FAIL_GET_USER_BY_ID';
