export const REQUEST_GET_USER_BY_ID = 'REQUEST_GET_USER_BY_ID';
export const SUCCESS_GET_USER_BY_ID = 'SUCCESS_GET_USER_BY_ID';
export const FAIL_GET_USER_BY_ID = 'FAIL_GET_USER_BY_ID';


export const REQUEST_LOGIN = 'REQUEST_LOGIN';
export const SUCCESS_LOGIN = 'SUCCESS_LOGIN';
export const FAIL_LOGIN = 'FAIL_LOGIN';

export const REGISTRATION_USER_REQUEST = 'REQUEST_REGISTRATION_USER';
export const REGISTRATION_USER_SUCCESS = 'REGISTRATION_USER_SUCCESS';
export const REGISTRATION_USER_FAIL = 'REGISTRATION_USER_FAIL';

export const REQUEST_LOGIN_AUT = 'REQUEST_LOGIN_AUT';
export const SUCCESS_LOGIN_AUT = 'SUCCESS_LOGIN_AUT';
export const FAIL_LOGIN_AUT = 'FAIL_LOGIN_AUT';


export const CREATE_NEW_USER_REQUEST = 'CREATE_NEW_USER_REQUEST';
export const CREATE_NEW_USER_SUCCESS = 'CREATE_NEW_USER_SUCCESS';
export const CREATE_NEW_USER_FAIL = 'CREATE_NEW_USER_FAIL';

export const CREATE_NEW_RATE_REQUEST = 'CREATE_NEW_RATE_REQUEST';
export const CREATE_NEW_RATE_SUCCESS = 'CREATE_NEW_RATE_SUCCESS';
export const CREATE_NEW_RATE_FAIL = 'CREATE_NEW_RATE_FAIL';
